### ISSUE TITLE
作者您好，我想问一下t-sne需要传入的维度是什么呢？

### ISSUE THREAD

**Issue by suntea233** [Linda230/ABSA-CL#2]

**Comment by suntea233** [comment]
想问一下T-SNE这个图是如何得到的？

**Comment by Linda230** [comment]
你好，你可以在网上搜索一下如何处理得到相应的t-SNE图。我这里是在RES14和LAP14数据集上进行处理，对应的标签的就是Positive, Negative和Neural， 这些标签是已知的。这个t-SNE图是为了证明经过对比学习得到的情感表征性能更加好。

**Comment by suntea233** [comment]
好的，谢谢
